[package]
name = "fitimer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
tui = "0.19"
crossterm = "0.25"
dotenv = "0.15.0"
colors-transform = "0.2.11"
